[package]
name = "ts-unused"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swc_common = { version = "0.29.33" }
swc_ecma_ast = "0.98.0"
swc_ecma_parser = "0.128.1"
swc_ecma_visit = "0.84.2"
